import { defineConfig } from 'eslint/config'
import tseslint from '@electron-toolkit/eslint-config-ts'
import eslintConfigPrettier from '@electron-toolkit/eslint-config-prettier'
import eslintPluginReact from 'eslint-plugin-react'
import eslintPluginReactHooks from 'eslint-plugin-react-hooks'
import eslintPluginReactRefresh from 'eslint-plugin-react-refresh'

export default defineConfig(
  // `.claude` holds agent worktrees — whole extra checkouts of this repo. Left
  // in, eslint lints every file twice and reports the second copy against the
  // wrong rules, because the shadcn exemption below is anchored at `src/` and
  // does not match a nested `.claude/worktrees/<agent>/src/`.
  //
  // `app-store-screenshots` and `.agents` are the app-store-screenshots
  // skill's scratch project and template — a Next.js app with its own build
  // output, not part of the Electron app and already git-ignored.
  {
    ignores: ['**/node_modules', '**/dist', '**/out', '.claude', 'app-store-screenshots', '.agents']
  },
  tseslint.configs.recommended,
  eslintPluginReact.configs.flat.recommended,
  eslintPluginReact.configs.flat['jsx-runtime'],
  {
    settings: {
      react: {
        version: 'detect'
      }
    }
  },
  {
    files: ['**/*.{ts,tsx}'],
    plugins: {
      'react-hooks': eslintPluginReactHooks,
      'react-refresh': eslintPluginReactRefresh
    },
    rules: {
      ...eslintPluginReactHooks.configs.recommended.rules,
      ...eslintPluginReactRefresh.configs.vite.rules
    }
  },
  {
    // Generated by `shadcn add` and not hand-maintained, so the house rules that
    // would mean editing every file on every regeneration are off here: they
    // export hooks and cva variant objects alongside their components
    // (react-refresh), they type props with TypeScript rather than React
    // (prop-types), and they let the JSX return type be inferred.
    files: ['src/renderer/src/components/ui/**', 'src/renderer/src/hooks/use-mobile.ts'],
    rules: {
      'react-refresh/only-export-components': 'off',
      'react/prop-types': 'off',
      '@typescript-eslint/explicit-function-return-type': 'off',
      // use-mobile seeds its state from window.innerWidth inside the effect so
      // that the first render is deterministic. Restructuring it would mean
      // re-doing the edit on every regeneration.
      'react-hooks/set-state-in-effect': 'off',
      // SidebarMenuSkeleton randomises its placeholder width during render.
      // Unused here, and a loading shimmer is the one place an unstable value
      // is harmless.
      'react-hooks/purity': 'off'
    }
  },
  eslintConfigPrettier
)
